# -*- coding: utf-8 -*-
"""budgetfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-fBqMGXQJxm87g05K5PTBfgex2iMiSS
"""

# -*- coding: utf-8 -*-
"""smart_budgeting_final_mainquest.py

Model Smart Budgeting dengan target realistic berbasis aturan adaptif:
- Kebutuhan dominan (40-50%) jika expense ratio tinggi
- Keinginan dominan (35-50%) jika lifestyle burden tinggi
- Tabungan dominan (40-60%) jika saving ratio tinggi
Memenuhi main quest: custom layer, custom loss, custom callback, evaluasi confusion matrix & classification report.
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, Model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import warnings
warnings.filterwarnings('ignore')

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

print(f'TensorFlow: {tf.__version__}')


# 1. LOAD DATA DAN FEATURE ENGINEERING

df = pd.read_csv('databersihowi.csv')

df['monthly_income'] = df['income'] / 12.0
df['expense_ratio'] = (df['total_expense'] / df['monthly_income']).clip(0, 1)
df['saving_ratio'] = 1 - df['expense_ratio']
df['income_log'] = np.log1p(df['income'])
df['lifestyle_burden'] = (df['lifestyle_expense'] / df['monthly_income']).clip(0, 1)
df['debt_burden'] = df['loan_int_rate'] / 20.0
df['credit_norm'] = (df['credit_score'] - 300) / 549.0

FEATURES = [
    'income_log', 'expense_ratio', 'lifestyle_burden',
    'debt_burden', 'credit_norm', 'family_size', 'age'
]
X = df[FEATURES].values.astype(np.float32)


# 2. TARGET ATURAN ADAPTIF (menghasilkan 3 kelas dominan)

def generate_realistic_target(row):
    monthly_inc = row['monthly_income']
    # Komponen aktual dari data
    needs_actual = (row['total_expense'] - row['lifestyle_expense']) / monthly_inc
    needs_actual = np.clip(needs_actual, 0.1, 0.7)
    wants_actual = row['lifestyle_burden']
    savings_actual = row['saving_ratio']
    if row['expense_ratio'] > 0.5:
        needs_target = np.clip(0.45 + np.random.uniform(-0.05, 0.05), 0.4, 0.5)
        wants_target = np.clip(0.25 + np.random.uniform(-0.05, 0.05), 0.2, 0.3)
        savings_target = 1 - needs_target - wants_target

    # Aturan adaptif berdasarkan profil keuangan
    if row['saving_ratio'] > 0.4:   # Tabungan dominan
        savings_target = np.clip(row['saving_ratio'], 0.4, 0.6)
        needs_target = max(0.15, needs_actual)
        wants_target = 1 - savings_target - needs_target
        if wants_target < 0.1:
            wants_target = 0.1
            savings_target = 1 - needs_target - wants_target
    elif row['lifestyle_burden'] > 0.3:  # Keinginan dominan
        wants_target = np.clip(row['lifestyle_burden'], 0.35, 0.5)
        needs_target = max(0.2, needs_actual)
        savings_target = 1 - wants_target - needs_target
        if savings_target < 0.1:
            savings_target = 0.1
            needs_target = 1 - wants_target - savings_target
    else:   # Kebutuhan dominan
        needs_target = np.clip(needs_actual, 0.4, 0.5)
        wants_target = max(0.1, wants_actual)
        savings_target = 1 - needs_target - wants_target
        if savings_target < 0.1:
            savings_target = 0.1
            wants_target = 1 - needs_target - savings_target

    # Normalisasi akhir
    total = needs_target + wants_target + savings_target
    needs = needs_target / total
    wants = wants_target / total
    savings = savings_target / total
    return np.array([needs, wants, savings], dtype=np.float32)

y_smart = np.array([generate_realistic_target(row) for idx, row in df.iterrows()])

# Tentukan kelas dominan berdasarkan argmax
df['dominant_class'] = np.argmax(y_smart, axis=1)
print("Distribusi kelas dominan (setelah aturan adaptif):")
print(df['dominant_class'].value_counts())


# 3. SPLIT DATA DENGAN STRATIFIKASI (memastikan semua kelas ada di test set)

indices = np.arange(len(df))
stratify_labels = df['dominant_class'].values

X_train_idx, X_test_idx, y_train, y_test = train_test_split(
    indices, y_smart, test_size=0.15, random_state=SEED, stratify=stratify_labels
)
X_train_idx, X_val_idx, y_train, y_val = train_test_split(
    X_train_idx, y_train, test_size=0.176, random_state=SEED, stratify=stratify_labels[X_train_idx]
)

X_train = X[X_train_idx]
X_val = X[X_val_idx]
X_test = X[X_test_idx]

# Scaling
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_val_s = scaler.transform(X_val)
X_test_s = scaler.transform(X_test)

# Sample weights (fokus pada saving rendah)
saving_ratio_train = df.iloc[X_train_idx]['saving_ratio'].values
sample_weights = np.ones(len(saving_ratio_train))
sample_weights[saving_ratio_train < 0.2] = 5.0
sample_weights = sample_weights / sample_weights.mean()

print(f'Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(X_test)}')
print("Distribusi kelas dominan di test set:")
print(pd.Series(np.argmax(y_test, axis=1)).value_counts())


# 4. KOMPONEN KUSTOM

class FinancialAttentionLayer(layers.Layer):
    def __init__(self, units=128, temperature=1.5, dropout_rate=0.2, **kwargs):
        super().__init__(**kwargs)
        self.units = units
        self.temperature = temperature
        self.dropout_rate = dropout_rate

    def build(self, input_shape):
        n = input_shape[-1]
        self.attn_w = self.add_weight(name='attn_w', shape=(n, n), initializer='glorot_uniform')
        self.attn_b = self.add_weight(name='attn_b', shape=(n,), initializer='zeros')
        self.proj_w = self.add_weight(name='proj_w', shape=(n, self.units), initializer='glorot_uniform')
        self.proj_b = self.add_weight(name='proj_b', shape=(self.units,), initializer='zeros')
        self.dropout = layers.Dropout(self.dropout_rate)
        super().build(input_shape)

    def call(self, inputs, training=False):
        scores = (tf.matmul(inputs, self.attn_w) + self.attn_b) / self.temperature
        weights = tf.nn.softmax(scores, axis=-1)
        attended = inputs * weights
        out = tf.nn.swish(tf.matmul(attended, self.proj_w) + self.proj_b)
        return self.dropout(out, training=training)

    def get_config(self):
        cfg = super().get_config()
        cfg.update({'units': self.units, 'temperature': self.temperature, 'dropout_rate': self.dropout_rate})
        return cfg

class WeightedCategoricalCrossentropy(keras.losses.Loss):
    def __init__(self, name='weighted_categorical_crossentropy', **kwargs):
        super().__init__(name=name, **kwargs)

    def call(self, y_true, y_pred, sample_weight=None):
        y_true = tf.cast(y_true, tf.float32)
        y_pred = tf.cast(y_pred, tf.float32)
        loss = -tf.reduce_sum(y_true * tf.math.log(y_pred + 1e-7), axis=-1)
        if sample_weight is not None:
            loss = loss * tf.cast(sample_weight, tf.float32)
        return tf.reduce_mean(loss)

class SmartBudgetMonitor(keras.callbacks.Callback):
    def __init__(self, X_val, y_val, every_epoch=5):
        super().__init__()
        self.X_val = X_val
        self.y_val = y_val
        self.every = every_epoch

    def on_epoch_end(self, epoch, logs=None):
        if (epoch + 1) % self.every == 0:
            preds = self.model.predict(self.X_val, verbose=0)
            mae_needs = np.mean(np.abs(preds[:, 0] - self.y_val[:, 0]))
            mae_wants = np.mean(np.abs(preds[:, 1] - self.y_val[:, 1]))
            mae_savings = np.mean(np.abs(preds[:, 2] - self.y_val[:, 2]))
            print(f"\n[Epoch {epoch+1}] MAE: Needs={mae_needs:.4f}, Wants={mae_wants:.4f}, Savings={mae_savings:.4f}")


# 5. ARSITEKTUR MODEL

def build_smart_budget_model(n_features=7):
    inp = keras.Input(shape=(n_features,), name='financial_features')
    x = FinancialAttentionLayer(units=128, temperature=1.5, dropout_rate=0.2)(inp)
    x = layers.Dense(256, activation='relu')(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.3)(x)
    x = layers.Dense(128, activation='relu')(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.2)(x)
    output = layers.Dense(3, activation='softmax', name='smart_output')(x)
    model = Model(inputs=inp, outputs=output, name='SmartBudget_Adaptive')
    return model

model = build_smart_budget_model(len(FEATURES))
model.summary()

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=5e-4, clipnorm=0.5),
    loss=WeightedCategoricalCrossentropy(),
    metrics=['mae', 'categorical_accuracy']
)


# 6. TRAINING

callbacks = [
    SmartBudgetMonitor(X_val_s, y_val, every_epoch=5),
    keras.callbacks.EarlyStopping(monitor='val_categorical_accuracy', patience=20,
                                  restore_best_weights=True, mode='max', verbose=1),
    keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=10, min_lr=1e-7, verbose=1),
    keras.callbacks.ModelCheckpoint('smart_budget_best.keras', monitor='val_categorical_accuracy',
                                    save_best_only=True, verbose=1)
]

history = model.fit(
    X_train_s, y_train,
    validation_data=(X_val_s, y_val),
    epochs=150,
    batch_size=256,
    sample_weight=sample_weights,
    callbacks=callbacks,
    verbose=1
)


# 7. EVALUASI LENGKAP (MAE, Confusion Matrix, Classification Report)

model.load_weights('smart_budget_best.keras')
preds = model.predict(X_test_s, verbose=0)
preds_pct = preds * 100
true_pct = y_test * 100

print('\n=== MAE per komponen (Target adaptif) ===')
for i, name in enumerate(['Kebutuhan', 'Keinginan', 'Tabungan']):
    mae = np.mean(np.abs(preds_pct[:, i] - true_pct[:, i]))
    print(f'{name}: {mae:.2f}%')
print(f'MAE overall: {np.mean(np.abs(preds_pct - true_pct)):.2f}%')

# Kelas dominan
pred_dominant = np.argmax(preds, axis=1)
true_dominant = np.argmax(y_test, axis=1)
class_names = ['Kebutuhan', 'Keinginan', 'Tabungan']
all_labels = [0, 1, 2]

cm = confusion_matrix(true_dominant, pred_dominant, labels=all_labels)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.title('Confusion Matrix - Smart Budgeting (Dominant Class)')
plt.ylabel('True')
plt.xlabel('Predicted')
plt.tight_layout()
plt.savefig('confusion_matrix_smart.png')
plt.show()

print('\nClassification Report:')
print(classification_report(true_dominant, pred_dominant, target_names=class_names, labels=all_labels, zero_division=0))


# 8. INFERENSI DENGAN POST-PROCESSING (Rule ringan)

def apply_post_processing(allocation_pct):
    """
    Memastikan alokasi tetap masuk akal: kebutuhan 15-60%, tabungan 10-70%, total 100%.
    """
    needs, wants, savings = allocation_pct
    needs = np.clip(needs, 15, 60)
    savings = np.clip(savings, 10, 70)
    wants = 100 - needs - savings
    if wants < 5:
        wants = 5
        savings = 100 - needs - wants
    return [needs, wants, savings]

def predict_smart_budget(user_data, model, scaler, apply_rule=True):
    income = user_data.get('income', 1)
    monthly_inc = income / 12.0
    total_exp = user_data.get('total_expense', 0)
    lifestyle = user_data.get('lifestyle_expense', 0)
    loan_rate = user_data.get('loan_int_rate', 10.0)
    credit = user_data.get('credit_score', 579)
    family = user_data.get('family_size', 2)
    age = user_data.get('age', 30)

    expense_ratio = np.clip(total_exp / (monthly_inc + 1e-6), 0, 1)
    features = np.array([[
        np.log1p(income),
        expense_ratio,
        np.clip(lifestyle / (monthly_inc + 1e-6), 0, 1),
        loan_rate / 20.0,
        (credit - 300) / 549.0,
        family,
        age
    ]], dtype=np.float32)

    features_scaled = scaler.transform(features)
    preds = model.predict(features_scaled, verbose=0)[0] * 100
    preds_list = preds.tolist()

    if apply_rule:
        preds_list = apply_post_processing(preds_list)

    return {
        'kebutuhan': round(preds_list[0], 1),
        'keinginan': round(preds_list[1], 1),
        'tabungan': round(preds_list[2], 1),
        'alokasi': f"{preds_list[0]:.1f}% / {preds_list[1]:.1f}% / {preds_list[2]:.1f}%"
    }


# 9. SIMPAN MODEL DAN ARTIFACTS

model.save('smart_budget_model.keras')
model.export('smart_budget_savedmodel')
with open('scaler_smart.pkl', 'wb') as f:
    pickle.dump(scaler, f)
with open('features_smart.pkl', 'wb') as f:
    pickle.dump(FEATURES, f)
print("\nModel dan artifacts disimpan.")


sample_users = [
    {'name': 'Budi (gaji tinggi, hemat)', 'data': {'income': 200000, 'total_expense': 4000, 'lifestyle_expense': 1000, 'loan_int_rate': 5, 'credit_score': 780, 'family_size': 2, 'age': 35}},
    {'name': 'Sari (gaji sedang, normal)', 'data': {'income': 100000, 'total_expense': 5000, 'lifestyle_expense': 2000, 'loan_int_rate': 10, 'credit_score': 650, 'family_size': 3, 'age': 30}},
    {'name': 'Andi (gaji rendah, boros)', 'data': {'income': 50000, 'total_expense': 4000, 'lifestyle_expense': 2500, 'loan_int_rate': 15, 'credit_score': 500, 'family_size': 1, 'age': 25}}
]

print("\n=== DEMO PREDIKSI SMART BUDGETING (Adaptif) ===")
for user in sample_users:
    result = predict_smart_budget(user['data'], model, scaler, apply_rule=True)
    print(f"\n{user['name']}")
    print(f"  Alokasi: {result['alokasi']}")